spring.datasource.url: jdbc:${SPRING_DATASOURCE_URL:mysql://${MYSQL_HOST:localhost}:3306/CurConv?createDatabaseIfNotExist=true}
spring.datasource.username: ${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password: ${SPRING_DATASOURCE_PASSWORD:kol97szc}
spring:
  jpa:
    hibernate:
      ddl-auto: none

    show-sql: true
server:
  port: ${PORT:8080}
